import { describe, it, expect } from 'vitest';
import 'fake-indexeddb/auto';
import { createRequire } from 'node:module';
import { Kernel, MemorySecretStore, openMemoryDb, type PluginContext } from '@mpw/kernel';
import { PersistedDbAdapter, IndexedDbBlobStore } from '../src/adapters/webAdapters';
import { DurableDb } from '../src/adapters/durableDb';
import { createBackup, readBackup } from '../src/adapters/backup';
import { registerResources } from '../src/resources';
import notes from '@mpw/plugin-notes';
import references from '@mpw/plugin-references';
import writing from '@mpw/plugin-writing';
import projects from '@mpw/plugin-projects';
import { createNote } from '../../../plugins/notes/src/store';
import { insertRef, updateRef } from '../../../plugins/references/src/store';
import { parseBibtex } from '../../../plugins/references/src/parsers';
import { createDoc, updateDoc } from '../../../plugins/writing/src/store';
import { createProject, addLink } from '../../../plugins/projects/src/store';
import { zipSync, unzipSync } from 'fflate';
const req = createRequire(import.meta.url);
const locate = (f: string): string => req.resolve(`sql.js/dist/${f}`);
const ctx = (k: Kernel, id: string): PluginContext => (k as unknown as { createContext(id: string): PluginContext }).createContext(id);

describe('durable data and research workflow', () => {
  it('retains dirty state after disk failure and retries the latest revision', async () => {
    let fail = true;
    let stored: Uint8Array | undefined;
    const inner = await openMemoryDb();
    const db = new DurableDb(inner, async (bytes) => { if (fail) throw new Error('disk full'); stored = bytes; });
    db.exec('CREATE TABLE test (value TEXT)');
    await expect(db.flush()).rejects.toThrow('disk full');
    expect(db.state.phase).toBe('error');
    expect(() => db.close()).toThrow();
    fail = false;
    db.run('INSERT INTO test VALUES (?)', ['latest']);
    await db.flush();
    expect(db.state.phase).toBe('saved'); expect(stored).toBeDefined(); db.close();
  });

  it('imports paper, attaches PDF, links project, exports and restores all data after reopening', async () => {
    const db = await PersistedDbAdapter.open(locate);
    const blobs = new IndexedDbBlobStore();
    const data = { db, blobs, restore: (b: Uint8Array, f: Record<string, Uint8Array>) => db.restore(b, f), location: 'test' };
    const kernel = new Kernel({ db, blobStore: blobs, secretStore: new MemorySecretStore() });
    kernel.registerBuiltins([notes, references, writing, projects]); await kernel.boot(); registerResources(kernel, db);
    const rctx = ctx(kernel, 'mpw.references');
    const reference = await insertRef(rctx, parseBibtex('@article{fixture2026, title={Research fixture}, author={Tester, Ada}, year={2026}}')[0]);
    const pdf = new TextEncoder().encode('%PDF-1.4\nresearch attachment fixture');
    const blob = await kernel.blobs.put('paper.pdf', pdf, 'application/pdf');
    await updateRef(rctx, reference.id, { blob_ref: blob.ref, file_name: 'paper.pdf' });
    const note = await createNote(ctx(kernel, 'mpw.notes'), 'Reading note');
    const citations = await kernel.commands.execute('mpw.references.citations') as { text: string }[];
    expect(citations[0].text).toContain('Research fixture');
    const doc = await createDoc(ctx(kernel, 'mpw.writing'), 'Research draft', 'rich');
    await updateDoc(ctx(kernel, 'mpw.writing'), doc.id, { content: `<p>Findings: ${citations[0].text}</p>` });
    const project = await createProject(ctx(kernel, 'mpw.projects'), 'Research project');
    for (const [kind, id] of [['note', note.id], ['reference', reference.id], ['doc', doc.id]]) await addLink(ctx(kernel, 'mpw.projects'), project.id, `mpw://${kind}/${id}`);
    await kernel.commands.execute('workspace.openResource', `mpw://doc/${doc.id}`);
    expect(await ctx(kernel, 'mpw.writing').storage.get('ui.openId', '')).toBe(doc.id);
    kernel.workspaces.saveLayout(kernel.workspaces.list()[0].id, '{"test":"layout"}');
    await kernel.secrets.set('ai.key.test', 'secret-not-in-backup');
    const backup = await createBackup(data);
    const parsed = await readBackup(backup, locate);
    expect([...parsed.blobs[blob.ref]]).toEqual([...pdf]);
    expect(new TextDecoder().decode(backup)).not.toContain('secret-not-in-backup');
    const broken = unzipSync(backup); broken['workspace.sqlite'][100] ^= 1;
    await expect(readBackup(zipSync(broken), locate)).rejects.toThrow('校验失败');
    // Restore into an entirely new database, with no existing PDFs or records.
    db.run('UPDATE p_notes_notes SET title = ?', ['changed after backup']);
    await db.flush();
    const destination = `restored-${Date.now()}`;
    const target = await PersistedDbAdapter.open(locate, destination);
    await target.restore(parsed.database, parsed.blobs);
    expect(() => target.run('DELETE FROM p_notes_notes')).toThrow('备份或恢复');
    target.close();
    db.close();
    const reopened = await PersistedDbAdapter.open(locate, destination);
    expect(reopened.one('SELECT title FROM p_notes_notes WHERE id = ?', [note.id])?.title).toBe('Reading note');
    expect(reopened.all('SELECT * FROM p_projects_links')).toHaveLength(3);
    expect(reopened.one('SELECT content FROM p_writing_documents WHERE id = ?', [doc.id])?.content).toContain('Research fixture');
    expect([...(await new IndexedDbBlobStore(destination).get(blob.ref))!.bytes]).toEqual([...pdf]);
    reopened.close();
  });
});
